"""Renders the final research report (Markdown) from the experiment ledger."""

from __future__ import annotations

import time
from pathlib import Path

from .llm.base import LLMUsage
from .memory.ledger import ExperimentLedger
from .task import TaskSpec


def build_report(
    task: TaskSpec,
    ledger: ExperimentLedger,
    conclusions: str,
    stop_reason: str,
    usage: LLMUsage | None = None,
) -> str:
    records = ledger.all()
    best = ledger.best(task.metric)

    lines: list[str] = [
        f"# Research Report: {task.name}",
        "",
        f"*Generated by Ramanujan (autonomous ML research agent) on "
        f"{time.strftime('%Y-%m-%d %H:%M')}*",
        "",
        "## Task",
        "",
        task.description.strip(),
        "",
        f"- **Dataset:** {task.dataset.strip()}",
        f"- **Target:** {task.metric.name} ({task.metric.direction}), goal {task.metric.goal}",
        f"- **Budget:** {task.budget.max_iterations} iterations, "
        f"{task.budget.experiment_timeout_seconds}s per experiment, executor `{task.executor}`",
        "",
        "## Outcome",
        "",
    ]
    if best is not None:
        goal = "**goal met**" if task.metric.goal_met(best.metric_value) else "goal not met"
        lines.append(
            f"Best result: **{best.metric_name} = {best.metric_value:.4f}** "
            f"(experiment {best.id}, iteration {best.iteration}) - {goal}. "
            f"Run stopped: `{stop_reason}`."
        )
    else:
        lines.append(f"No experiment produced a valid result. Run stopped: `{stop_reason}`.")

    if usage is not None and usage.calls:
        cost = f" ≈ **${usage.cost_usd:.4f}**" if usage.cost_usd else ""
        lines += [
            "",
            f"**Research cost:** {usage.calls} LLM calls, "
            f"{usage.prompt_tokens:,} prompt + {usage.completion_tokens:,} completion tokens{cost}.",
        ]

    lines += ["", "## Leaderboard", "", "| # | Iter | Hypothesis | Status | "
              f"{task.metric.name} | Duration |", "|---|------|------------|--------|--------|----------|"]
    for rec in records:
        value = f"{rec.metric_value:.4f}" if rec.metric_value is not None else "-"
        duration = f"{rec.duration_seconds:.1f}s" if rec.duration_seconds else "-"
        marker = " ⭐" if best and rec.id == best.id else ""
        lines.append(
            f"| {rec.id}{marker} | {rec.iteration} | {_trim(rec.hypothesis, 70)} "
            f"| {rec.status} | {value} | {duration} |"
        )

    lines += ["", "## Experiment log", ""]
    for rec in records:
        lines += [f"### Experiment {rec.id} (iteration {rec.iteration})", ""]
        lines.append(f"- **Hypothesis:** {rec.hypothesis}")
        lines.append(f"- **Approach:** {rec.approach}")
        if rec.status == "success":
            lines.append(f"- **Result:** {rec.metric_name} = {rec.metric_value:.4f}")
            if rec.metrics:
                extras = {k: v for k, v in rec.metrics.items() if k not in ("metric_name", "metric_value")}
                if extras:
                    lines.append(f"- **Secondary metrics:** {extras}")
        else:
            lines.append(f"- **Result:** failed - {rec.error_summary}")
        if rec.insight:
            lines.append(f"- **Insight:** {rec.insight}")
        lines.append("")

    lines += ["## Conclusions", "", conclusions.strip(), ""]

    if best is not None and best.code_path and Path(best.code_path).exists():
        lines += [
            "## Appendix: best solution code",
            "",
            f"`{Path(best.code_path).name}` from experiment {best.id}:",
            "",
            "```python",
            Path(best.code_path).read_text(encoding="utf-8").rstrip(),
            "```",
            "",
        ]
    return "\n".join(lines)


def _trim(text: str, limit: int) -> str:
    text = " ".join(text.split())
    return text if len(text) <= limit else text[: limit - 3] + "..."
